inekf_node:
  ros__parameters:
    frame_id: "odom"
    child_frame_id: "base_link"
    
    # L'InEKF préfère souvent le topic brut complet (ou AHRS filtré)
    imu_topic: "/olivecam/filtered_ahrs_synced"
    
    # La vitesse est cruciale pour l'InEKF (souvent appelée "Kinematics" ou "Contact")
    velocity_topic: "/imu/velocity_synced"
    
    # Covariances sur l'Algèbre de Lie (à tuner obligatoirement)
    noise:
      gyro_bias: 1e-4
      accel_bias: 1e-2
